chore: format with prettier and add prettier stuff
dhscodingclub-org/club-portal pull request #6
Opened 2023-09-12 00:43 UTC by EdwinChang24

2023-09-12 01:19 UTC, Sophon96 requested changes
Just a small change needed. Looks good otherwise!

2023-09-12 01:19 UTC, Sophon96 commented on .github/workflows/prettier-check.yml
> +on: push
Can we have this run on pull requests? It doesn't make sense to check it after it's merged.

2023-09-12 05:13 UTC, Sophon96 approved these changes
LGTM!

2023-09-12 05:14 UTC, Sophon96 requested changes

2023-09-12 05:14 UTC, Sophon96 commented on pnpm-lock.yaml
Wait bruh add this to `.prettierignore`

2023-09-12 05:16 UTC, Sophon96 commented on pnpm-lock.yaml
And then can you reset the lockfile to `main` and rerun `pnpm install`?

2023-09-12 06:10 UTC, EdwinChang24 commented on pnpm-lock.yaml
I symlinked `.prettierignore` to `.gitignore` :skull:

2023-09-14 22:51 UTC, Sophon96 approved these changes

2023-09-14 22:51 UTC, Sophon96 commented on .prettierignore
This is certainly a unique approach

2023-09-14 23:30 UTC, merged